version: '2.1'

services:
  storage-tunnel:
    image: storage-tunnel-debug
    build: .
    environment:
      NODE_ENV: development
      SERVER_ROOT: .
      DEBUG: "localtunnel:*"
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 src/index.js